name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # 当推送以 v 开头的标签时触发
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write
  id-token: write  # 用于 OIDC 认证

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Extract version from tag
      id: get_version
      run: |
        VERSION=${GITHUB_REF_NAME#v}
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build distribution
      run: |
        python -m build

    - name: Check distribution
      run: |
        twine check dist/*

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # 使用 OIDC 认证，更安全
      # 如果你更喜欢使用 API Token，可以取消下面这行注释并设置 PYPI_TOKEN secret
      # with:
      #   password: ${{ secrets.PYPI_TOKEN }}

    - name: Create GitHub Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ env.VERSION }}
        name: Release v${{ env.VERSION }}
        body: |
          Release version ${{ env.VERSION }}
          
          ## Changes
          - Check the commit history for detailed changes
        files: |
          ./dist/tsugu-uds-${{ env.VERSION }}.tar.gz
          ./dist/tsugu-uds-${{ env.VERSION }}-py3-none-any.whl
        draft: false
        prerelease: false
